#!/bin/sh

usage() {
    echo "$0 DOMAIN DAYS"
    exit ${1:-0}
}

BASEDIR=$(dirname ${0})
. ${BASEDIR}/letsencrypt-common

DAYS=${2}

[ -z "${DAYS}" ] && usage 127

CERTDIR=/etc/letsencrypt/live/${DOMAIN}

DIFFSEC=$(($(date +%s -d"$(openssl x509 -in ${CERTDIR}/cert.pem -noout -enddate | cut -f 2 -d =)")-$(date +%s)))

MAXSEC=$((${DAYS}*24*60*60))

if [ "${DIFFSEC}" -gt "${MAXSEC}" ]; then
    exit 1
fi

exit 0
