#!/bin/sh

LETSENCRYPT=/opt/letsencrypt/letsencrypt-auto
COMMON_PARAMS="--authenticator webroot --renew-by-default --agree-tos --webroot-path=/etc/letsencrypt/webroot/"

usage() {
    echo bad params
    exit 1
}

RESTART_NGINX=false

while read DAYS HOSTNAME DOMAINS; do

    [ -z "$DAYS" ] && usage
    [ -z "$HOSTNAME" ] && usage

    RETRIES=5
    while /opt/letsencrypt-misc/letsencrypt-renewneeded $HOSTNAME $DAYS; do
	RESTART_NGINX=true
        PARAMS="$COMMON_PARAMS -d $HOSTNAME"
    
	for DOMAIN in $DOMAINS; do
	    PARAMS="$PARAMS -d $DOMAIN"
	done
	/opt/letsencrypt/letsencrypt-auto certonly $PARAMS

	RETRIES=$(($RETRIES-1))

	if [ "$RETRIES" -eq "0" ]; then
	    break;
	fi
    done
done < /etc/letsencrypt/domains.conf

if $RESTART_NGINX; then
    nginx -t && nginx -s reload;
fi
